name: GitHub Actions workflow that tests and analyzes the code
on: 
  push:
  workflow_dispatch:

jobs:
  # Job that scans and analyzes the code
  scan_the_code:
    needs: [build_and_test]
    permissions: 
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          repository: devenes/node-js-dummy-test
          ref: master
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with: 
          languages: javascript
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with: 
          output: result.sarif
      - name: Upload the result artifact
        uses: actions/upload-artifact@v4
        with:
          name: code_scanning_results
          path: ./results.sarif

  build_and_test:
    strategy:
      matrix:
        operating_system: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          repository: devenes/node-js-dummy-test
          ref: master
      - name: "Use Node version: ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build --if-present
      - name: Test the code
        run: npm test
          
